services:
  
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - db-data:/etc/htu-db:Z
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=hightechu22"
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  web:
    build: .
    restart: unless-stopped
    ports:
      - "8080"
    depends_on:
      - db
    environment:
      - "DATABASE_URL=postgresql://postgres:hightechu22@db/postgres"

volumes:
  db-data:
